include("modules/downloads.lua")
include("modules/baseclass.lua")

AddCSLuaFile("extensions/math.lua")
AddCSLuaFile("extensions/string.lua")
AddCSLuaFile("extensions/table.lua")
AddCSLuaFile("util/utils.lua")
AddCSLuaFile("util/types.lua")
AddCSLuaFile("util/json.lua")
AddCSLuaFile("util/hook.lua")

include("extensions/math.lua")
include("extensions/string.lua")
include("extensions/table.lua")
include("util/utils.lua")
include("util/types.lua")
include("util/json.lua")
include("util/hook.lua")